# Generated by Django 2.2 on 2019-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
