# Generated by Django 2.2 on 2019-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_section_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='prominent',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
