# Generated by Django 2.2 on 2019-05-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190523_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headFront',
            field=models.BooleanField(default=False),
        ),
    ]
