# Generated by Django 2.2 on 2019-05-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_headfront'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='headFront',
        ),
    ]
