# Generated by Django 2.2 on 2019-05-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_article_headfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
    ]
